version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '${POSTGRES_HOST_PORT:-8090}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ${POSTGRES_DB:-bay_serverpod}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeMe}"
    volumes:
      - bay_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeMe}"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  bay_serverpod_data:
